Veteran status update post Codesystem move into NCTS
hl7au/au-fhir-base pull request #798
Opened 2023-09-21 21:16 UTC by mjosborne1

- New extension to patient for Australian Veteran Status
- Change to remove local veteran status Codesystem and Valueset placeholders
- Updated changes.md to include veteran status artifacts

2023-09-21 21:18 UTC, mjosborne1 commented
release date for the Australian Veteran Status Codesystem and Valueset into NCTS is Weds 27th Sept 2023

2023-09-21 23:23 UTC, dt-r requested changes
Hi Michael,

Thanks for your PR. Just need to make a change to StructureDefinition, and add punctuation in changes.md

2023-09-21 23:23 UTC, dt-r commented on input/pagecontent/changes.md
Nice changes in this file, just missing ":" at the end of "Changed Patient.extension"

2023-09-21 23:23 UTC, dt-r commented on input/pagecontent/terminology.md
I note an additional change in this file on top of veteran status. It's ok, it improves the alphabetical order.

2023-09-21 23:23 UTC, dt-r commented on input/resources/structuredefinition-veteran-status.xml
Need to change `StructureDefinition.status` to `draft` to match FMM 0

2023-09-22 03:31 UTC, mjosborne1 commented
I have made changes as requested and committed to au-veteran-status branch.

2023-09-22 06:32 UTC, dt-r approved these changes

2023-09-22 06:34 UTC, merged