Change to Valueset-rsg-type
hl7au/au-fhir-base pull request #868
Opened 2024-10-22 04:20 UTC by mjosborne1

for https://jira.hl7.org/browse/FHIR-46544
add SNOMED CT AU code 1515311000168102|Biological sex at birth|

2024-10-22 04:44 UTC, mjosborne1 commented
Please hold off - there seems to be a strange issue with the expansion of this ValueSet.

2024-10-22 05:30 UTC, mjosborne1 commented
OK, It's expanding now. Weird...I didn't change anything, but maybe it was terminology server related.

2024-10-22 08:47 UTC, dbojicic commented on input/resources/valueset-rsg-type.xml
>          </include>
Commenting here to get an inline comment. 
Please update change log.

2024-10-22 08:47 UTC, dbojicic requested changes
One change requested.

2024-10-24 23:41 UTC, dbojicic approved these changes

2024-10-25 06:42 UTC, brettesler-ext approved these changes

2024-10-25 06:42 UTC, merged