Change CodeSystems and ValueSets to use meta profile Complete CodeSystem 4 and Composed ValueSet 4
hl7au/au-fhir-base pull request #875
Opened 2024-11-11 07:06 UTC by mjosborne1

CodeSystem and ValueSet profile changed to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> and <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/composed-value-set-4"> Composed ValueSet 4</a> (<a href="https://jira.hl7.org/browse/FHIR-47148">FHIR-47148</a> and <a href="https://jira.hl7.org/browse/FHIR-47149">FHIR-47149</a>) 

CodeSystem properties updated to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> (<a href="https://jira.hl7.org/browse/FHIR-47148">FHIR-47148</a>)

2024-11-11 22:48 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem properties updated to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> (<a href="https://jira.hl
Suggest changing to something like: 
Updated CodeSystem resourced to conform to <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">NCTS Complete Code System</a> (<a href="https://jira.hl7.org/browse/FHIR-47148">FHIR-47148</a>).

2024-11-11 22:49 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem and ValueSet profile changed to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> and <a href="ht
Suggest changing to something like:
Updated ValueSet resourced to conform to [NCTS Complete Value Set](https://healthterminologies.gov.au/fhir/StructureDefinition/composed-value-set-4) ([FHIR-47149](https://jira.hl7.org/browse/FHIR-47149)).

2024-11-11 23:48 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem properties updated to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> (<a href="https://jira.hl
Confirmed

2024-11-11 23:48 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem and ValueSet profile changed to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> and <a href="ht
Confirmed

2024-11-12 00:31 UTC, dbojicic requested changes
Please see comments

2024-11-12 00:54 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem properties updated to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> (<a href="https://jira.hl
Confirmed

2024-11-12 00:55 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem and ValueSet profile changed to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> and <a href="ht
Not fully addressed as the updated entry still starts with "ValueSet profile updated.."

2024-11-12 00:56 UTC, dbojicic requested changes
Just one minor change required

2024-11-12 01:01 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>CodeSystem and ValueSet profile changed to align with NCTS <a href="https://healthterminologies.gov.au/fhir/StructureDefinition/complete-code-system-4">Complete CodeSystem 4</a> and <a href="ht
Confirmed

2024-11-12 01:02 UTC, dbojicic approved these changes

2024-11-15 02:41 UTC, brettesler-ext approved these changes

2024-11-15 02:41 UTC, merged