Remove minimum constraint on Identifier.assigner in AU Local Order Identifier (FHIR-47188)
hl7au/au-fhir-base pull request #880
Opened 2024-11-21 03:29 UTC by JayMurdoch

Fix for [FHIR-47188](https://jira.hl7.org/browse/FHIR-47188)
* Remove min constraint
* Change log entry

2024-11-21 08:49 UTC, dbojicic requested changes
Please see comments.

2024-11-21 10:33 UTC, JayMurdoch commented on input/pagecontent/changes.md
> +  <li>Removed minimum constraint on Identifier.assigner in <a href="StructureDefinition-au-localorderidentifier.html">AU Local Order Identifier</a> (<a href="https://jira.hl7.org/browse/FHIR-47188">F
Amended, thanks.

2024-11-21 10:52 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>Removed minimum constraint on Identifier.assigner in <a href="StructureDefinition-au-localorderidentifier.html">AU Local Order Identifier</a> (<a href="https://jira.hl7.org/browse/FHIR-47188">F
Confirmed.

2024-11-21 10:52 UTC, dbojicic approved these changes

2024-11-26 03:58 UTC, brettesler-ext approved these changes

2024-11-28 01:46 UTC, merged