Additional actions for deprecation of AU Base Diagnostic Request (#886, FHIR-46714)
hl7au/au-fhir-base pull request #888
Opened 2024-12-01 12:36 UTC by JayMurdoch

Additional fix for [FHIR-46714](https://jira.hl7.org/browse/FHIR-46714)

* Changed short and definition to note deprecation and reason
* Changed resource status to 'retired'
* Add deprecation STU note to intro.md

Initial PR: https://github.com/hl7au/au-fhir-base/pull/872
Issue raised to fix deprecation (incomplete): https://github.com/hl7au/au-fhir-base/issues/886

2025-01-06 22:05 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
>    <url value="http://hl7.org.au/fhir/StructureDefinition/au-diagnosticrequest" />
add standards status reason extension to put in the deprecation note.

2025-01-06 22:05 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
>    <description value="This profile defines a service request structure to represent a request for a diagnostic investigation in an Australian context. This profile is intended to support ordering for
In description add prefix "Deprecated:"

2025-01-06 22:06 UTC, dt-r commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Missing the rest of the deprecation note narrative - add in a summary sentence or two, and then refer to it's replacement as it's replacement. See https://build.fhir.org/operationoutcome-definitions.html#OperationOutcome.issue.location for an example.

2025-01-06 22:17 UTC, dt-r requested changes
See inline changes, and in addition:
1. no active StructureDefinition should refer to this profile - need to swap it out for it's replacement
2. add to the change log the changes from point 1.

2025-01-06 22:17 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
Wording to be worked on. This profile is deprecated not just because it is use case specific, but because a separate project is now undertaking that work and this profile has moved in to AU eRequesting to define a diagnostic service request.

2025-01-06 22:17 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
When referring to another FHIR structure inside a StructureDefition - ALWAYS make it an absolute URL, NEVER do the shorthand. (This all gets inherited into profiles that derive from it who do not have a profile at this location: StructureDefinition-au-servicerequest.html thus breaking the link in all downstream specs and for the profile on the server)

You can only use the shorthand on the intro & notes & guidance pages as those are not published separately or inherited into other IGs.

2025-01-06 23:55 UTC, JayMurdoch commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Amended, thanks.

2025-01-07 00:05 UTC, JayMurdoch commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
Amended, thanks.

2025-01-07 04:51 UTC, dt-r commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Let's future proof this a bit.

`This profile is deprecated in AU Base as work is being undertaken in the <a href="https://build.fhir.org/ig/hl7au/au-fhir-erequesting">AU eRequesting</a> project to define the requirements for a diagnostic request. In AU Base this profile is replaced by <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>, which localises core concepts, including identifiers and terminology, for use in an Australian context and enables implementers and modellers to make their own rules, i.e. (<a href="http://hl7.org/fhir/profiling.html">profiling</a>, about how to support these concepts for specific implementation needs.`

2025-01-07 04:52 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
Update this wording to align to the changes made to the stu note.

2025-01-07 04:58 UTC, dt-r commented on input/pagecontent/changes.md
> +    <li>Changed referenced profile for DiagnosticReport.basedOn from AU Base Diagnostic Request to AU Base Service Request (<a href="https://jira.hl7.org/browse/FHIR-46714">FHIR-46714</a>.)</li>
Replace instances of "Changed referenced profile" with "Changed Type"

2025-01-07 05:02 UTC, JayMurdoch commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Amended, thanks.

2025-01-07 05:02 UTC, JayMurdoch commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
Amended, thanks.

2025-01-07 05:03 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
>    <url value="http://hl7.org.au/fhir/StructureDefinition/au-diagnosticrequest" />
standards status is present, but can't spot standards status reason

2025-01-07 05:04 UTC, dt-r requested changes
See inline comments that are not resolved. In addition, point 1. and point 2. confirmed as fixed.

2025-01-07 05:08 UTC, JayMurdoch commented on input/pagecontent/changes.md
> +    <li>Changed referenced profile for DiagnosticReport.basedOn from AU Base Diagnostic Request to AU Base Service Request (<a href="https://jira.hl7.org/browse/FHIR-46714">FHIR-46714</a>.)</li>
Amended, thanks.

2025-01-07 12:33 UTC, JayMurdoch commented on input/resources/au-diagnosticrequest.xml
>    <url value="http://hl7.org.au/fhir/StructureDefinition/au-diagnosticrequest" />
Standards Status Reason extension included, noting I do not see anything relating to this rendered in the profile. Please confirm that the extension has been applied correctly.

2025-01-08 05:13 UTC, JayMurdoch commented on input/resources/au-diagnosticrequest.xml
>    <url value="http://hl7.org.au/fhir/StructureDefinition/au-diagnosticrequest" />
Confirmed nothing renders for Standards Status Reason ext.

2025-01-08 06:53 UTC, dt-r commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Copy paste error from what I provided, there is a missing closing bracket after the </a>

2025-01-08 06:56 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated in AU Base as work is being undertaken in the [AU eRequesting](https://build.fhir.org/ig/hl7au/au-fhir-erequesting) project to define the requireme
All together the paragraph doesn't make sense with that final sentence sitting there. There needs to be a line break included so that "A record of a request for one or more ..." is a rendered as a new paragraph.

2025-01-08 06:58 UTC, dt-r commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
Amended but 
1. All together the paragraph doesn't make sense with that final sentence sitting there. There needs to be a line break included so that "A record of a request for one or more ..." is a rendered as a new paragraph.
2. Reintroduced an issue - when inside a StructureDefinition ALWAYS provide the absolute URL. Change "[AU Base Service Request](https://github.com/hl7au/au-fhir-base/pull/888/StructureDefinition-au-servicerequest.html)" - you will break downstream IGs.

2025-01-08 07:00 UTC, dt-r requested changes
Final tweaks in the unresolved comments.

2025-01-08 10:32 UTC, JayMurdoch commented on input/intro-notes/StructureDefinition-au-diagnosticrequest-intro.md
> +<p class="stu-note">This profile is deprecated. See <a href="StructureDefinition-au-servicerequest.html">AU Base Service Request</a>.</p>
Amended, thanks.

2025-01-08 11:40 UTC, JayMurdoch commented on input/resources/au-diagnosticrequest.xml
> +      <definition value="This profile is deprecated because it is use case specific. It is replaced by [AU Base Service Request](StructureDefinition-au-servicerequest.html), which is broader in scope
1. Line break added.
2. Amended, thanks.

2025-01-09 03:48 UTC, dt-r approved these changes

2025-01-09 03:49 UTC, merged