Substance 2 example SNOMED CT code , display update
hl7au/au-fhir-base pull request #890
Opened 2024-12-02 03:30 UTC by mjosborne1

Updated Substance 2 example SNOMED CT code and display to the latest code and display from AMT V4.

2024-12-09 00:34 UTC, dbojicic commented on input/ignoreWarnings.txt
>  The HTML fragment 'ip-statements.xhtml' is not included anywhere in the produced implementation guide
Commenting here to get an inline comments. 

This PR does not include changes to ignoreWarnings or changes files, please remove from the PR.

2024-12-09 00:42 UTC, dbojicic requested changes
Please see comments.

2025-01-06 09:31 UTC, dbojicic approved these changes

2025-01-06 09:31 UTC, dbojicic commented on input/ignoreWarnings.txt
>  The HTML fragment 'ip-statements.xhtml' is not included anywhere in the produced implementation guide
Removed.

2025-01-06 20:17 UTC, brettesler-ext approved these changes

2025-01-06 20:17 UTC, merged