Update bodySite to bodyStructure and add mutually exclusivity constraint (FHIR-47117)
hl7au/au-fhir-base pull request #893
Opened 2024-12-10 02:32 UTC by dbojicic

This PR fixes [FHIR-47117](https://jira.hl7.org/browse/FHIR-47117). 

Changes: 
- Updated AU Base Diagnostic Imaging Result to: 
  - move the usage of the BodyStructure reference extension to the Observation element instead of Observation.bodySite
  - rename the slice from bodySite to bodyStructure
  - add invariant inv-obs-1
- Updated AU Base Diagnostic Result to: 
   - rename the slice from bodySite to bodyStructure
   - add invariant inv-obs-1
- Updated Change Log

2025-01-07 00:54 UTC, dt-r commented on input/pagecontent/changes.md
> +  <li>Changes to <a href="StructureDefinition-au-imagingresult.html">AU Base Diagnostic Imaging Result</a>:
Change log changes not consistent with existing style. Split renamed and added inv and moved extension changes into separate points.

2025-01-07 01:04 UTC, dt-r commented on input/pagecontent/changes.md
> +#### Changes in this version
4.2.2 preview doesn't exist in the current build change log. This should have only been in the release branch for 4.2.2. Fix this branch.

2025-01-07 01:20 UTC, dt-r commented on input/intro-notes/StructureDefinition-au-imagingresult-intro.md
> +- The [bodyStructure](http://hl7.org/fhir/R4/extension-bodysite.html) extension may be suitable for use where
The extension's title is "BodyStructure Reference" and it's id is bodySite - there is no "bodyStructure" beyond our slice which is not what is being referenced here. Change to "BodyStructure Reference".

2025-01-07 01:37 UTC, dt-r commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
human expression is not consistent with au base approach, the slice name isn't the object of interest and we don't put FHIR path unless there are two elements with the same name. Possibly:
BodyStructure Reference extension shall only be present if body site element is not present
OR
A diagnostic imaging result shall only include a body structure reference if the body site is not present
OR
A diagnostic imaging result shall not have both a body structure reference and a body site element

2025-01-07 02:29 UTC, dt-r requested changes
See inline comments.

2025-01-08 01:24 UTC, dbojicic commented on input/pagecontent/changes.md
> +  <li>Changes to <a href="StructureDefinition-au-imagingresult.html">AU Base Diagnostic Imaging Result</a>:
done

2025-01-08 01:27 UTC, dbojicic commented on input/pagecontent/changes.md
> +#### Changes in this version
Done

2025-01-08 02:06 UTC, dbojicic commented on input/intro-notes/StructureDefinition-au-imagingresult-intro.md
> +- The [bodyStructure](http://hl7.org/fhir/R4/extension-bodysite.html) extension may be suitable for use where
'BodyStructure Reference' is the extension name; the actual title is 'Body Site'.

2025-01-08 02:41 UTC, dbojicic commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
Applied change to reference the id: "bodySite extension shall only be present if Observation.bodySite is not present". Please refer to [this](https://github.com/hl7au/au-fhir-base/pull/893#discussion_r1906242809) comment for reasoning.

2025-01-08 03:11 UTC, dt-r commented on input/intro-notes/StructureDefinition-au-imagingresult-intro.md
> +- The [bodyStructure](http://hl7.org/fhir/R4/extension-bodysite.html) extension may be suitable for use where
'bodySite' is not accepted. In the narrative use either the title or name of the extension.

2025-01-08 03:11 UTC, dt-r commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
As above, that reasoning is not accepted.

2025-01-08 03:12 UTC, dt-r commented on input/pagecontent/changes.md
> +    <li>moved the usage of the bodySite extension to the Observation element instead of Observation.bodySite (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</li>
remove the words "usage of the"

2025-01-08 03:13 UTC, dt-r commented on input/pagecontent/changes.md
> +    <li>to ensure the bodySite extension is present only when Observation.bodySite is not present preadopted from the R5 invariant (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</l
the change log is not correct - it is not an exact preadopt. We added an invariant to pre-adopt behaviours.

2025-01-08 03:20 UTC, dt-r requested changes
See unresolved and new inline comments

2025-01-08 04:36 UTC, dbojicic commented on input/intro-notes/StructureDefinition-au-imagingresult-intro.md
> +- The [bodyStructure](http://hl7.org/fhir/R4/extension-bodysite.html) extension may be suitable for use where
Changed to reference the extension name.

2025-01-08 04:36 UTC, dbojicic commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
Changed  to reference the extension name.

2025-01-08 04:44 UTC, dbojicic commented on input/pagecontent/changes.md
> +    <li>moved the usage of the bodySite extension to the Observation element instead of Observation.bodySite (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</li>
Done

2025-01-08 04:45 UTC, dbojicic commented on input/pagecontent/changes.md
> +    <li>to ensure the bodySite extension is present only when Observation.bodySite is not present preadopted from the R5 invariant (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</l
1. oops, was looking at previously requested change and looked at the resource as well but obv didn't click - changed now
2. done

2025-01-08 05:26 UTC, dt-r commented on input/pagecontent/changes.md
> +    <li>added invariant inv-obs-1 to preadopt behaviors expected in R5 by ensuring the BodyStructure Reference extension is present only when Observation.bodySite is not present (<a href="https://jir
spelling: behaviours not behaviors
can change to be
"... to preadopt R5 behaviour to ensure the ..."

2025-01-08 05:28 UTC, dt-r commented on input/pagecontent/changes.md
> +    <li>to ensure the bodySite extension is present only when Observation.bodySite is not present preadopted from the R5 invariant (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</l
close but tiny tweak needed due to spelling: behaviours not behaviors
can change to be
"... to preadopt R5 behaviour to ensure the ..."

2025-01-08 06:28 UTC, dt-r commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
For the human expression, except for the circumstance that a structure has two elements with the same name, AU Base does not use FHIRPath. Change "Observation.bodySite" to something else.

2025-01-08 06:30 UTC, dt-r requested changes
resolved some inline comments, further tweaks on other inline comments

2025-01-08 07:13 UTC, dbojicic commented on input/pagecontent/changes.md
> +    <li>to ensure the bodySite extension is present only when Observation.bodySite is not present preadopted from the R5 invariant (<a href="https://jira.hl7.org/browse/FHIR-47117">FHIR-47117</a>)</l
Done

2025-01-08 11:57 UTC, dbojicic commented on input/resources/au-diagnosticresult.xml
> +        <human value="bodyStructure shall only be present if Observation.bodySite is not present" />
Missed it in your previous suggestions, changed now.

2025-01-09 03:21 UTC, dt-r approved these changes

2025-01-09 03:21 UTC, merged